
spring.application.name=biblioteca-api


spring.data.mongodb.uri=mongodb+srv://adminBiblioteca:Biblio2024!@cluster0.jql1kcc.mongodb.net/biblioteca_db?retryWrites=true&w=majority


spring.data.mongodb.database=biblioteca_db


server.port=8080